require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
permissions_path = '../node_modules/react-native-permissions/ios'
pod 'Permission-Camera', :path => "#{permissions_path}/Camera"
platform :ios, '10.0'

target 'Solareum' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  pod 'RNPermissions', :path => '../node_modules/react-native-permissions'

  target 'SolareumTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  # use_flipper!
   post_install do |installer|
     if target.name == "React-Core.common-AccessibilityResources" target.remove_from_project end
   end
end

target 'Solareum-tvOS' do
  # Pods for Solareum-tvOS

  target 'Solareum-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
