export enum Routes {
  Home = 'Home',
  CreateWallet = 'Create Wallet',
  EditWallet = 'Edit Wallet',
  DEX = 'Serum DEX',
  Market = 'DEX',
  GetStarted = 'Get Started',
  ImportWallet = 'Import Wallet',
  Notifications = 'Notification',
  Settings = 'Settings',
  Token = 'Token',
  Wallet = 'Wallet',
  SettingWallet = 'Manage Wallet',
  Search = 'Tokens',
  Mission = 'Mission',
  ManagementTokenList = 'Manage Accounts',
  SwapApplication = 'Swap Application',
  Influencer = 'Referral',
  Airdrop = 'Airdrop',
  Swap = 'Swap',
  Explore = 'Explore',
  ExploreList = 'Explore List',
  ExploreItem = 'Token Info',
  Pay = 'Pay',
  MoonPay = 'MoonPay',
  Restore = 'Restore',
}

export default Routes;
